### ISSUE TITLE
Invert download and upload speed info in torrents list

### ISSUE THREAD

**Issue by Matth7878** [Bartuzen/qBitController#53] opened 2023-03-15 19:51 UTC
### Describe your suggested feature

In torrents list info about download speed and quantity is showed after the upload ones.
On desktop client (windows) in the status bar and in the torrents list download info is showed before upload.

It would be nice to have qBitController used same order as the desktop client.

**Comment by Bartuzen** [comment] 2023-03-15 20:00
Seems like this is duplicate of #47.

**Closed by Bartuzen** 2023-03-15 20:00 UTC
Labels: feature
